---
name: build-hugo-docs
description:  Building static content with hugo
inputs:
  hugo_version:
    description: "Version of hugo"
    required: true
    default: "0.120.4"
runs:
  using: composite
  steps:
    - name: Get hugo binary
      shell: bash
      run: >
        wget -O- https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
        | tar xvz -C /usr/local/bin hugo
    - name: Install npm dependencies
      shell: bash
      run: npm install -C themes/docsy && npm install postcss-cli autoprefixer
    - name: Build hugo docs/
      shell: bash
      run: hugo --gc --minify
