name: Deploy preview

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Build docs
        uses: ./.github/actions/build-hugo-docs
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.4
        with:
          source-dir: public/
